sudo: false
dist: trusty

language: c

addons:
  apt:
    packages:
      - texinfo
        dejagnu

script:
  - mkdir build && cd build
    ../configure --prefix=`pwd`/root --target=${TARGET_TRIPLET} --disable-gdb
    make -j && make check

matrix:
  include:
    - env:
        - TARGET_TRIPLET='xtensa-elf'
    - env:
        - TARGET_TRIPLET='xtensa-linux-uclibc'
    - env:
        - TARGET_TRIPLET='xtensa-linux-gnu'
    - env:
        - TARGET_TRIPLET='xtensa-uclinux-uclibc'
